language: node_js
node_js:
- '0.10'
before_install:
-  openssl aes-256-cbc -K $encrypted_8bfe06cf1581_key -iv $encrypted_8bfe06cf1581_iv -in key.json.enc -out key.json -d
before_script:
- npm run-script lint
env:
- DATASET_ID=proppy-mvm-dogfood
